#!/bin/bash -l
#SBATCH --time=24:00:00
#SBATCH -p a100-4
#SBATCH --gres=gpu:a100:1
#SBATCH --ntasks=32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=enana003@umn.edu
#SBATCH --output=R-Heuristic.txt
#SBATCH --error=R-%Heuristicerror.txt
module load python3
python3 experiments.py
